name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/v*'
jobs:
  build-all:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config: [ xgo2 ]
    steps:
      - uses: actions/checkout@v3
        with:
          path: xgo2-buildroot
      - uses: actions/checkout@v3
        with:
          repository: buildroot/buildroot
          ref: 2023.11.x
          path: buildroot
      - name: Configure Buildroot
        run: tree ../../ && make -C buildroot BR2_EXTERNAL=../xgo2-buildroot O=../output ${{ matrix.config }}_defconfig
      - name: Build Buildroot
        run: make -C buildroot BR2_EXTERNAL=../xgo2-buildroot O=../output
      - name: Compress sdcard.img
        run: gzip -9 output/images/sdcard.img
      - name: Store images
        uses: actions/upload-artifact@v3
        with:
          name: image-${{ matrix.config }}
          path: output/images/sdcard.img.gz
